title: "DevOps Journey | Karim Garcia"
description: "Cloud-native experiments, DevOps methodologies, and automation projects."
theme: minima
permalink: /:title/

header_pages:
  - index.md

github_username: karim-garcia
linkedin_school: karimgarciaguillen

plugins:
  - jekyll-seo-tag

exclude: [feed.xml]
