title: "DevOps Journey | Karim Garcia"
description: "Cloud-native experiments, DevOps methodologies, and automation projects."
theme: minima
permalink: /:title/

header_pages:
  - index.md

github_username:  https://github.com/karim-garcia/
linkedin_school:  https://www.linkedin.com/in/karimgarciaguillen

plugins:
  - jekyll-feed
  - jekyll-seo-tag
